opariffazman/bootcamp-devops

- peserta/muhammadzulfadhly.md
**Peserta:** Muhammad Zulfadhly
> docs: add biodata for muhammad zulfadhly

- peserta/syedazam.md
> docs: add biodata - Syed Azam

- peserta/mohd-adli.md
**Peserta:** Mohd Adli bin Jaaffar
> docs: add biodata for mohd adli bin jaaffar

- peserta/amirzuhri.md
**Peserta:** Amir Zuhri bin AHmad
> docs: add peserta biodata - Amir Zuhri bin Ahmad

- peserta/ahmadafif.md
> Bio AhmadDM

- peserta/firdausleman.md
> docs: add biodata for firdausleman

- peserta/kraff.md
> docs: add biodata for kraff

- peserta/amir.md
> docs: add biodata for Mohd Amiruddin

- peserta/shamim.md
> updated profile shamim

- peserta/ariffbootcamp.md
> docs: add biodata for ariffbootcamp

- peserta/muhamad-saffuan-ahmad-kamal.md
**Peserta:** Muhamad Saffuan Ahmad Kamal
> docs: add biodata for Muhamad Saffuan

- peserta/khairahn.md
**Peserta:** Khairah Nazurah Karim
> docs: add biodata for khairahn

- peserta/raja-hadi.md
> doc: add biodata for [Raja Hadi]

- peserta/aiman-elyas.md
> docs: add biodata for [Aiman Elyas]

- peserta/afiq-devops.md
> docs: add peserta biodata - Zaid Afiq

- labs/lab2.md
> fix: simplified instructions

- aimandani.md
**Peserta:** [Muhammad Aiman bin Dani Asmadi]
> docs : add biodata for Aiman Dani

- peserta/fakhrul-aziz.md
> docs: add peserta biodata - Fakhrul Aziz

- peserta/hamizanaiman.md
> docs: add biodata for Hamizan Aiman

- peserta/ijat.md
> docs: add peserta biodata - Izzat Taufik

- peserta/fatah.md
**Peserta:** Muhammad Mufattah
> docs: add biodata for Muhammad Mufattah

- peserta/faiz-puad.md
> docs: add peserta self intro docs for lab requirement

- peserta/sumantri-suhaimi.md
**Peserta:** [Sumantri Suhaimi]
> docs: add biodata for Sumantri Suhaimi

- peserta/muhammad-adeeb-bin-zamil.md
**Peserta:** Muhammad Adeeb bin Zamil
> docs: add biodata for Muhammad Adeeb bin Zamil
